Name:           ros-kinetic-pyros-utils
Version:        0.1.3
Release:        0%{?dist}
Summary:        ROS pyros_utils package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-rosgraph >= 1.11.19
Requires:       ros-kinetic-roslaunch >= 1.11.19
Requires:       ros-kinetic-rospy >= 1.11.19
Requires:       ros-kinetic-rostest >= 1.11.19
BuildRequires:  ros-kinetic-catkin >= 0.6.18
BuildRequires:  ros-kinetic-catkin-pip >= 0.1.15
BuildRequires:  ros-kinetic-pyros-test >= 0.0.3
BuildRequires:  ros-kinetic-rosgraph >= 1.11.19
BuildRequires:  ros-kinetic-roslaunch >= 1.11.19
BuildRequires:  ros-kinetic-roslint >= 0.10.0
BuildRequires:  ros-kinetic-rosnode >= 1.11.19
BuildRequires:  ros-kinetic-rospy >= 1.11.19
BuildRequires:  ros-kinetic-rostest >= 1.11.19
BuildRequires:  ros-kinetic-rosunit >= 1.11.12

%description
Miscellaneous tools for pyROS

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Jan 11 2017 AlexV <asmodehn@gmail.com> - 0.1.3-0
- Autogenerated by Bloom

* Mon Sep 05 2016 AlexV <asmodehn@gmail.com> - 0.1.2-1
- Autogenerated by Bloom

* Mon Sep 05 2016 AlexV <asmodehn@gmail.com> - 0.1.2-0
- Autogenerated by Bloom

