Name:           ros-indigo-pyros-utils
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS pyros_utils package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-rosgraph >= 1.11.19
Requires:       ros-indigo-roslaunch >= 1.11.19
Requires:       ros-indigo-rospy >= 1.11.19
Requires:       ros-indigo-rostest >= 1.11.19
BuildRequires:  ros-indigo-catkin >= 0.6.18
BuildRequires:  ros-indigo-catkin-pip >= 0.1.3
BuildRequires:  ros-indigo-pyros-test >= 0.0.3
BuildRequires:  ros-indigo-rosgraph >= 1.11.19
BuildRequires:  ros-indigo-roslaunch >= 1.11.19
BuildRequires:  ros-indigo-roslint >= 0.10.0
BuildRequires:  ros-indigo-rosnode >= 1.11.19
BuildRequires:  ros-indigo-rospy >= 1.11.19
BuildRequires:  ros-indigo-rostest >= 1.11.19
BuildRequires:  ros-indigo-rosunit >= 1.11.12

%description
Miscellaneous tools for pyROS

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Jun 02 2016 AlexV <asmodehn@gmail.com> - 0.1.1-0
- Autogenerated by Bloom

* Wed Jun 01 2016 AlexV <asmodehn@gmail.com> - 0.1.0-0
- Autogenerated by Bloom

